# Generated by Django 3.2.9 on 2021-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(error_messages={'unique': 'This phone number has already been registered.'}, max_length=20, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('activation_key', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expire', models.DateTimeField(blank=True, null=True, verbose_name='token expire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='dispatch_ap_phone_672f40_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='dispatch_ap_created_710934_idx'),
        ),
    ]
